layout_spectrum: 0.33256835234351456
typography_spectrum: 0.2276293581817299
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9963764178100973
  lightness: 0.5850097117945552
  saturation: 0.9451702223159373
  rhythmicContrast: 0.3941602057311684
name: Explore
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
